"""streak_and_mock_exam

Revision ID: 1b007f4825a3
Revises: 6c138b351314
Create Date: 2026-05-25 05:13:31.754924
"""
from alembic import op
import sqlalchemy as sa


revision = '1b007f4825a3'
down_revision = '6c138b351314'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak_makeups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('missed_date', sa.String(length=10), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'missed_date', name='uq_streak_makeup')
    )
    with op.batch_alter_table('streak_makeups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streak_makeups_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('last_date', sa.String(length=10), nullable=True),
    sa.Column('cards', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaks_candidate_id'), ['candidate_id'], unique=True)

    # SQLite 不允许给已有数据的表加 NOT NULL 且无默认值的列，故显式 server_default
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=16), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('duration_sec', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('timeout', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('timeout')
        batch_op.drop_column('deadline_at')
        batch_op.drop_column('duration_sec')
        batch_op.drop_column('mode')

    with op.batch_alter_table('streaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaks_candidate_id'))

    op.drop_table('streaks')
    with op.batch_alter_table('streak_makeups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streak_makeups_candidate_id'))

    op.drop_table('streak_makeups')
    # ### end Alembic commands ###
