"""add doc_task_events table

Revision ID: 29b4962fba52
Revises: abb8b649ff92
Create Date: 2026-03-04 17:18:45.644982
"""
from alembic import op
import sqlalchemy as sa


revision = '29b4962fba52'
down_revision = 'abb8b649ff92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_task_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_task_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
