"""doc_chunk_embedding_and_task_mode

Revision ID: 6c138b351314
Revises: 12ead2620c5f
Create Date: 2026-05-25 03:34:55.160501
"""
from alembic import op
import sqlalchemy as sa


revision = '6c138b351314'
down_revision = '12ead2620c5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('scope', sa.Text(), nullable=True))

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heading_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('embed_status', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_column('embed_status')
        batch_op.drop_column('embedding')
        batch_op.drop_column('heading_path')

    with op.batch_alter_table('doc_tasks', schema=None) as batch_op:
        batch_op.drop_column('scope')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
