"""daily_task_done_ids

Revision ID: 9b438ae98caf
Revises: 1b007f4825a3
Create Date: 2026-05-25 05:32:54.071612
"""
from alembic import op
import sqlalchemy as sa


revision = '9b438ae98caf'
down_revision = '1b007f4825a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不允许给已有数据的表加 NOT NULL 且无默认值的列
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done_ids', sa.Text(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_column('done_ids')

    # ### end Alembic commands ###
