"""add cancel_requested to doc_tasks

Revision ID: d9e6096bc0af
Revises: 29b4962fba52
Create Date: 2026-04-04 21:18:29.789089
"""
from alembic import op
import sqlalchemy as sa


revision = 'd9e6096bc0af'
down_revision = '29b4962fba52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_tasks', schema=None) as batch_op:
        # SQLite 不允许给已有数据的表加 NOT NULL 列而不给默认值，必须带 server_default
        batch_op.add_column(
            sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_tasks', schema=None) as batch_op:
        batch_op.drop_column('cancel_requested')

    # ### end Alembic commands ###
