"""add cancel_requested to doc_tasks

Revision ID: d9e6096bc0af
Revises: 29b4962fba52
Create Date: 2026-04-04 21:18:29.789089
"""
from alembic import op
import sqlalchemy as sa


revision = 'd9e6096bc0af'
down_revision = '29b4962fba52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 幂等化（2026-06-12）：与 `7a1c0ffee123` / `abb8b649ff92` 同一个原因 ——
    # `0001_initial` 用 `Base.metadata.create_all()` 建的是**当前 models 的全量** schema，
    # 所以本列早已存在；无条件 `add_column` 会让**全新库上的 `alembic upgrade head` 失败**
    # （实测：`DuplicateColumn: column "cancel_requested" of relation "doc_tasks" already exists`）。
    # 本迁移是全链**最后一处**漏守卫的（对照过全部 9 个含 DDL 的迁移）。
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if insp.has_table('doc_tasks'):
        cols = {c['name'] for c in insp.get_columns('doc_tasks')}
        if 'cancel_requested' not in cols:
            with op.batch_alter_table('doc_tasks', schema=None) as batch_op:
                # SQLite 不允许给已有数据的表加 NOT NULL 列而不给默认值，必须带 server_default
                batch_op.add_column(
                    sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default=sa.false())
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_tasks', schema=None) as batch_op:
        batch_op.drop_column('cancel_requested')

    # ### end Alembic commands ###
